version: '3.9'

services:
  broker:
    image: eclipse-mosquitto:latest
    ports:
      - '1883:1883'
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - broker_network
    restart: always
  
  adapter:
    image: adapter
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - broker  
      - influxdb   
    environment:
      - DEBUG_DATA_FLOW=true
    networks:
      - db_network
      - broker_network
    restart: always
  
  influxdb:
    image: influxdb:1.8
    ports:
      - '8086:8086'
    volumes:
      - influxdb-data:/var/lib/influxdb
    networks:
      - db_network
      - grafana_network
    restart: always
  
  grafana:
    image: grafana/grafana:latest
    depends_on:
      - influxdb
    ports:
      - '80:3000'
    environment:
      - GF_SECURITY_ADMIN_USER=asistent
      - GF_SECURITY_ADMIN_PASSWORD=grafanaSPRC2021
    networks:
      - grafana_network    
    volumes:
      - grafana-data:/var/lib/grafana
    restart: always

volumes:
  influxdb-data:
  grafana-data:

networks:
  broker_network:
  db_network:
  grafana_network:
  